version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: metrics
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - db

volumes:
  db-data:
