apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/luizdopc/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 30 Apr 2024 18:50:18 UTC
        provider: minikube.sigs.k8s.io
        version: v1.33.0
      name: cluster_info
    server: https://192.168.39.8:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 30 Apr 2024 18:50:18 UTC
        provider: minikube.sigs.k8s.io
        version: v1.33.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/luizdopc/.minikube/profiles/minikube/client.crt
    client-key: /home/luizdopc/.minikube/profiles/minikube/client.key
