apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.newPorts.http}}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.newPorts.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
