version: '3.3'

networks:
  aw-network:
   driver: bridge

volumes:
  prometheus_data:
   
services:
  java-http:
    image: luizdopc/java-http:v0.6
    container_name: java-http
    ports:
      - 8080:8080
    networks:
      - aw-network