version: '3.3'

networks:
  aw-network:
   driver: bridge

volumes:
  prometheus_data:
   
services:
  java-http:
    image: luizdopc/go-grpc:v0.2
    container_name: go-grpc
    ports:
      - 8080:8080
      - 50001:50001
    networks:
      - aw-network