version: '3.3'

networks:
  aw-network:
   driver: bridge

volumes:
  prometheus_data:
   
services:
  java-http:
    image: luizdopc/java-grpc:v0.3
    container_name: java-grpc
    ports:
      - 8080:8080
      - 50051:50051
    networks:
      - aw-network